// pack_no_signal converts the approved Vue-rendered PNG artwork into compact
// PackBits-style NV21 byte arrays consumed directly by libkvm_mmf.so.
package main

import (
	"bytes"
	"fmt"
	"image"
	"image/draw"
	_ "image/png"
	"os"
	"path/filepath"
)

type frameSpec struct {
	width  int
	height int
	path   string
	name   string
}

// A wider row keeps generated source below the repository's 1000-line limit
// without changing the packed bytes or the compiled representation.
const bytesPerSourceLine = 512

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintf(os.Stderr, "usage: %s OUTPUT\n", filepath.Base(os.Args[0]))
		os.Exit(2)
	}
	frames := []frameSpec{
		{1920, 1080, "assets/no-signal/onekvm-no-signal-1920x1080.png", "no_signal_1920x1080"},
		{1280, 720, "assets/no-signal/onekvm-no-signal-1280x720.png", "no_signal_1280x720"},
		{640, 480, "assets/no-signal/onekvm-no-signal-640x480.png", "no_signal_640x480"},
	}

	var output bytes.Buffer
	output.WriteString("// Generated by tools/pack_no_signal.go. Do not edit.\n")
	output.WriteString("#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\n")
	output.WriteString("typedef struct {\n\tint width;\n\tint height;\n\tconst uint8_t *packed;\n\tsize_t packed_size;\n} no_signal_asset_t;\n\n")

	for _, spec := range frames {
		pixels, err := loadNV21(spec)
		if err != nil {
			fatal(err)
		}
		packed := packBits(pixels)
		fmt.Fprintf(&output, "static const uint8_t %s[] = {\n", spec.name)
		for offset := 0; offset < len(packed); offset += bytesPerSourceLine {
			end := min(offset+bytesPerSourceLine, len(packed))
			output.WriteString("\t")
			for index := offset; index < end; index++ {
				fmt.Fprintf(&output, "0x%02x,", packed[index])
			}
			output.WriteString("\n")
		}
		output.WriteString("};\n\n")
		fmt.Fprintf(os.Stderr, "%dx%d: %d -> %d bytes (%.1f%%)\n",
			spec.width, spec.height, len(pixels), len(packed), float64(len(packed))*100/float64(len(pixels)))
	}

	output.WriteString("static const no_signal_asset_t no_signal_assets[] = {\n")
	for _, spec := range frames {
		fmt.Fprintf(&output, "\t{%d, %d, %s, sizeof(%s)},\n", spec.width, spec.height, spec.name, spec.name)
	}
	output.WriteString("};\n")

	if err := os.WriteFile(os.Args[1], output.Bytes(), 0o644); err != nil {
		fatal(err)
	}
}

func loadNV21(spec frameSpec) ([]byte, error) {
	file, err := os.Open(spec.path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	decoded, _, err := image.Decode(file)
	if err != nil {
		return nil, fmt.Errorf("decode %s: %w", spec.path, err)
	}
	if decoded.Bounds().Dx() != spec.width || decoded.Bounds().Dy() != spec.height {
		return nil, fmt.Errorf("%s is %dx%d, want %dx%d", spec.path,
			decoded.Bounds().Dx(), decoded.Bounds().Dy(), spec.width, spec.height)
	}
	rgba := image.NewRGBA(image.Rect(0, 0, spec.width, spec.height))
	draw.Draw(rgba, rgba.Bounds(), decoded, decoded.Bounds().Min, draw.Src)

	frame := make([]byte, spec.width*spec.height*3/2)
	for y := 0; y < spec.height; y++ {
		for x := 0; x < spec.width; x++ {
			offset := rgba.PixOffset(x, y)
			frame[y*spec.width+x], _, _ = videoYUV(rgba.Pix[offset], rgba.Pix[offset+1], rgba.Pix[offset+2])
		}
	}
	chroma := frame[spec.width*spec.height:]
	for y := 0; y < spec.height; y += 2 {
		for x := 0; x < spec.width; x += 2 {
			var red, green, blue int
			for dy := 0; dy < 2; dy++ {
				for dx := 0; dx < 2; dx++ {
					offset := rgba.PixOffset(x+dx, y+dy)
					red += int(rgba.Pix[offset])
					green += int(rgba.Pix[offset+1])
					blue += int(rgba.Pix[offset+2])
				}
			}
			_, u, v := videoYUV(uint8(red/4), uint8(green/4), uint8(blue/4))
			offset := (y/2)*spec.width + x
			chroma[offset], chroma[offset+1] = v, u
		}
	}
	return frame, nil
}

func videoYUV(red, green, blue uint8) (uint8, uint8, uint8) {
	r, g, b := int(red), int(green), int(blue)
	y := ((66*r + 129*g + 25*b + 128) >> 8) + 16
	u := ((-38*r - 74*g + 112*b + 128) >> 8) + 128
	v := ((112*r - 94*g - 18*b + 128) >> 8) + 128
	return clamp(y), clamp(u), clamp(v)
}

func clamp(value int) uint8 {
	if value < 0 {
		return 0
	}
	if value > 255 {
		return 255
	}
	return uint8(value)
}

// packBits stores repeated runs of 3..130 bytes as [0x80|(len-3), value]
// and literal runs of 1..128 bytes as [len-1, bytes...].
func packBits(input []byte) []byte {
	packed := make([]byte, 0, len(input)/8)
	for offset := 0; offset < len(input); {
		run := repeated(input, offset)
		if run >= 3 {
			run = min(run, 130)
			packed = append(packed, 0x80|byte(run-3), input[offset])
			offset += run
			continue
		}
		literalStart := offset
		offset++
		for offset-literalStart < 128 && offset < len(input) && repeated(input, offset) < 3 {
			offset++
		}
		length := offset - literalStart
		packed = append(packed, byte(length-1))
		packed = append(packed, input[literalStart:offset]...)
	}
	return packed
}

func repeated(input []byte, offset int) int {
	end := offset + 1
	for end < len(input) && end-offset < 130 && input[end] == input[offset] {
		end++
	}
	return end - offset
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
